# Generated by Django 5.0.6 on 2024-06-19 13:14

import movies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Izox matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Janr nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Kino nomi')),
                ('uid', models.UUIDField(editable=False, verbose_name='ID')),
                ('trailer', models.FileField(upload_to='trailers', verbose_name='Kino trayleri')),
                ('banner', models.ImageField(upload_to='banners', verbose_name='Kino banneri')),
                ('description', models.TextField(verbose_name='Kino haqida qisqacha')),
                ('year', models.CharField(max_length=10, verbose_name='Kino yili')),
                ('source', models.FileField(upload_to='movies', verbose_name='Kino')),
                ('rank', models.DecimalField(decimal_places=1, max_digits=5, validators=[movies.utils.min_value_validator, movies.utils.max_value_validator])),
                ('search', models.IntegerField(default=0, verbose_name='Kino qidiruvlar soni')),
                ('price', models.IntegerField(default=0, verbose_name='Kino narxi')),
                ('is_premiere', models.BooleanField(default=False, verbose_name='Kino premyerami?')),
                ('length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
