# Generated by Django 5.0.6 on 2024-06-19 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izox maullifi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kino muallifi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='feedbackers',
            field=models.ManyToManyField(blank=True, null=True, related_name='movei_feedbackers', to=settings.AUTH_USER_MODEL, verbose_name='Kinoga baho berganlar'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genres', to='movies.genre', verbose_name='Kino janrlari'),
        ),
        migrations.AddField(
            model_name='movie',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_viewers', to=settings.AUTH_USER_MODEL, verbose_name='Kinoni tomosha qilganlar'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Kino'),
        ),
    ]
